export const TEAM_CODES = {
  'brasil': 'br',
  'brazil': 'br',
  'argentina': 'ar',
  'frança': 'fr',
  'france': 'fr',
  'espanha': 'es',
  'spain': 'es',
  'alemanha': 'de',
  'germany': 'de',
  'portugal': 'pt',
  'inglaterra': 'gb-eng',
  'england': 'gb-eng',
  'itália': 'it',
  'italy': 'it',
  'holanda': 'nl',
  'netherlands': 'nl',
  'bélgica': 'be',
  'belgium': 'be',
  'uruguai': 'uy',
  'uruguay': 'uy',
  'marrocos': 'ma',
  'morocco': 'ma',
  'méxico': 'mx',
  'mexico': 'mx',
  'áfrica do sul': 'za',
  'south africa': 'za',
  'coreia do sul': 'kr',
  'south korea': 'kr',
  'tchéquia': 'cz',
  'czech republic': 'cz',
  'canadá': 'ca',
  'canada': 'ca',
  'bósnia e herzegovina': 'ba',
  'bosnia & herzegovina': 'ba',
  'catar': 'qa',
  'qatar': 'qa',
  'suíça': 'ch',
  'switzerland': 'ch',
  'haiti': 'ht',
  'escócia': 'gb-sct',
  'scotland': 'gb-sct',
  'estados unidos': 'us',
  'usa': 'us',
  'paraguai': 'py',
  'paraguay': 'py',
  'austrália': 'au',
  'australia': 'au',
  'turquia': 'tr',
  'turkey': 'tr',
  'curaçao': 'cw',
  'costa do marfim': 'ci',
  'ivory coast': 'ci',
  'equador': 'ec',
  'ecuador': 'ec',
  'japão': 'jp',
  'japan': 'jp',
  'suécia': 'se',
  'sweden': 'se',
  'tunísia': 'tn',
  'tunisia': 'tn',
  'egito': 'eg',
  'egypt': 'eg',
  'irã': 'ir',
  'iran': 'ir',
  'nova zelândia': 'nz',
  'new zealand': 'nz',
  'cabo verde': 'cv',
  'cape verde': 'cv',
  'arábia saudita': 'sa',
  'saudi arabia': 'sa',
  'senegal': 'sn',
  'iraque': 'iq',
  'iraq': 'iq',
  'noruega': 'no',
  'norway': 'no',
  'argélia': 'dz',
  'algeria': 'dz',
  'áustria': 'at',
  'austria': 'at',
  'jordânia': 'jo',
  'jordan': 'jo',
  'rd congo': 'cd',
  'dr congo': 'cd',
  'uzbequistão': 'uz',
  'uzbekistan': 'uz',
  'colômbia': 'co',
  'colombia': 'co',
  'croácia': 'hr',
  'croatia': 'hr',
  'gana': 'gh',
  'ghana': 'gh',
  'panamá': 'pa',
  'panama': 'pa'
}

export function getFlagUrl(teamName) {
  if (!teamName) return null;
  const name = teamName.toLowerCase().trim();
  const code = TEAM_CODES[name];
  if (code) {
    return `https://flagcdn.com/w80/${code}.png`;
  }
  return null;
}
